#env GOOS=linux GOARCH=amd64 go build
#docker build -t mercurius:backend .
#docker run -p 8080:8080 -d mercurius:backend

FROM scratch

ADD backend /
ADD conf/ /conf
ADD public/ /public
ADD locale/ /locale

CMD [ "/backend" ]